### ISSUE TITLE
Add a meta file for upcoming plugin admin UI

### ISSUE THREAD

**Issue by ArthurHoaro** [alexisju/gototop#1]
Also applies to your other plugins.

See shaarli/Shaarli#388

[Example](https://github.com/ArthurHoaro/Shaarli/blob/pluginadmin/plugins/wallabag/wallabag.meta)

**Comment by alexisju** [comment]
Added! Thank you.

https://github.com/alexisju/gototop/commit/4be49285a784bfab22a9929655a230737d06534a
