### ISSUE TITLE
Button text in English (or any other language)

### ISSUE THREAD

**Issue by effemmeffe** [alexisju/gototop#3]
I noticed that the name on the button is haut. I suppose that means top in French.
I'm Italian, but I have the shaarli installation in English, I'd like to read top in the button.
I know I can change it in the gotop.php file, but I was thinking that maybe in the future shaarli would allow internalization. Maybe it's something that can start from this little thing?

**Comment by alexisju** [comment]
Hi! Thank you for your feedback.
I'll publish an update using an image instead a text.
I think it is not possible to bring multi language into plugins without a common system into Shaarli's core.
